### ISSUE TITLE
not manage.py in askbot-openmooc

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/askbot-openmooc#13]
not manage.py in askbot-openmooc, how migrate bd after git pull today

**Comment by ablanco** [comment]
Use `openmooc-askbot-admin` in the instance directory.

**Comment by johnfelipe** [comment]
I dont find it, and this error show me

```
    Traceback (most recent call last):
    [Wed Feb 19 13:21:25 2014] [error] [client 181.141.217.220]   File "/home/mooc/askbot-openmooc-venv/lib/python2.6/site-packages/Django-1.4.3-py2.6.egg/django/core/handlers/wsgi.py", line 219, in _call_
    [Wed Feb 19 13:21:25 2014] [error] [client 181.141.217.220]     self.load_middleware()
    [Wed Feb 19 13:21:25 2014] [error] [client 181.141.217.220]   File "/home/mooc/askbot-openmooc-venv/lib/python2.6/site-packages/Django-1.4.3-py2.6.egg/django/core/handlers/base.py", line 47, in load_middleware
    [Wed Feb 19 13:21:25 2014] [error] [client 181.141.217.220]     raise exceptions.ImproperlyConfigured('Error importing middleware %s: "%s"' % (mw_module, e))
    [Wed Feb 19 13:21:25 2014] [error] [client 181.141.217.220] ImproperlyConfigured: Error importing middleware askbotopenmooc.app.middlewares: "No module named django"
```
