### ISSUE TITLE
Install askbot again

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/askbot-openmooc#14]
i update askbot yesterday, first i dont find openmooc-askbot-admin...

And this is error find it:

```
Traceback (most recent call last):
[Wed Feb 19 13:21:25 2014] [error] [client 181.141.217.220]   File "/home/mooc/askbot-openmooc-venv/lib/python2.6/site-packages/Django-1.4.3-py2.6.egg/django/core/handlers/wsgi.py", line 219, in _call_
[Wed Feb 19 13:21:25 2014] [error] [client 181.141.217.220]     self.load_middleware()
[Wed Feb 19 13:21:25 2014] [error] [client 181.141.217.220]   File "/home/mooc/askbot-openmooc-venv/lib/python2.6/site-packages/Django-1.4.3-py2.6.egg/django/core/handlers/base.py", line 47, in load_middleware
[Wed Feb 19 13:21:25 2014] [error] [client 181.141.217.220]     raise exceptions.ImproperlyConfigured('Error importing middleware %s: "%s"' % (mw_module, e))
[Wed Feb 19 13:21:25 2014] [error] [client 181.141.217.220] ImproperlyConfigured: Error importing middleware askbotopenmooc.app.middlewares: "No module named django"
```

**Comment by ablanco** [comment]
Why are you using a vritualenv? You should use the rpms.

**Comment by johnfelipe** [comment]
rpms is ready, i update old...

**Comment by ablanco** [comment]
The packages are here: http://openmooc.org/openmooc-rpms

**Comment by johnfelipe** [comment]
then is not possible update old one

**Comment by ablanco** [comment]
It is possible, but it's not supported, you are on your own.

**Comment by johnfelipe** [comment]
I have moocng, sspopenmooc and userregistration update old type, if i reinstall askbot rpm style is fine?
