### ISSUE TITLE
issue install DOC

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/askbot-openmooc#4]
Hi 
1. Recreate statics file directory with collectstatic command:

python manage.py collectstatic

And i get this:

"Error in course_settings
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/core/management/**init**.py", line 429, in execute_from_command_line
    utility.execute()
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/core/management/**init**.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/core/management/base.py", line 191, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/core/management/base.py", line 209, in execute
    translation.activate('en-us')
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/utils/translation/**init**.py", line 100, in activate
    return _trans.activate(language)
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/utils/translation/trans_real.py", line 202, in activate
    _active.value = translation(language)
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/utils/translation/trans_real.py", line 185, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/utils/translation/trans_real.py", line 162, in _fetch
    app = import_module(appname)
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/django_countries-1.0.5-py2.7.egg/django_countries/**init**.py", line 1, in <module>
    """
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/django_countries-1.0.5-py2.7.egg/django_countries/fields.py", line 1, in <module>
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/db/**init**.py", line 78, in <module>
    connection = connections[DEFAULT_DB_ALIAS]
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/db/utils.py", line 93, in **getitem**
    backend = load_backend(db['ENGINE'])
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/db/utils.py", line 33, in load_backend
    return import_module('.base', backend_name)
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/utils/importlib.py", line 35, in import_module
    **import**(name)
  File "/root/askbot-devel/askbot-openmooc-venv/lib/python2.7/site-packages/Django-1.3.1-py2.7.egg/django/db/backends/mysql/base.py", line 14, in <module>
    raise ImproperlyConfigured("Error loading MySQLdb module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named MySQLdb
"

**Comment by ant30** [comment]
You need to install MySQL-python

If you follow Centos Multipleinstance install, you can install this package with yum from CentOS repository.

https://github.com/OpenMOOC/askbot-openmooc/blob/master/README-centos-multipleinstance.rst

**Comment by johnfelipe** [comment]
Hi, view attach:

![mysqlpython](https://f.cloud.github.com/assets/428820/307161/15bfec6a-96b3-11e2-858e-1d08374de8b1.png)

I install it, but persiste error

Tnks

**Comment by ant30** [comment]
OpenMooc has been tested in Centos 6, your mysql package describe your system as Centos 5

You can't install the openmooc in "root" user, you must create one user, like "mooc" as is told in doc.

**Comment by johnfelipe** [comment]
You can tell me please best option for centos for install all openmooc plataform?, an architecture 32 or 64 bit?

Tnks

**Comment by ant30** [comment]
Django 1.3.x is required for the askbot related version (0.7.43)

**Comment by johnfelipe** [comment]
Hi using, https://github.com/OpenMOOC/askbot-openmooc/blob/master/README-centos.rst in step 15, using django 1.3.3 and python 2.7.3 show me this error:

"(askbot-openmooc-venv)[root@felipeurrego askbot-openmooc]# python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/askbot-openmooc-venv/lib/python2.7/site-packages/django/core/management/**init**.py", line 429, in execute_from_command_line
    utility.execute()
  File "/root/askbot-openmooc-venv/lib/python2.7/site-packages/django/core/management/**init**.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/askbot-openmooc-venv/lib/python2.7/site-packages/django/core/management/**init**.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/root/askbot-openmooc-venv/lib/python2.7/site-packages/django/core/management/**init**.py", line 67, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/root/askbot-openmooc-venv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    **import**(name)
  File "/root/askbot-openmooc-venv/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 7, in <module>
    from django.core.management.sql import custom_sql_for_model, emit_post_sync_signal
  File "/root/askbot-openmooc-venv/lib/python2.7/site-packages/django/core/management/sql.py", line 6, in <module>
    from django.db import models
  File "/root/askbot-openmooc-venv/lib/python2.7/site-packages/django/db/**init**.py", line 14, in <module>
    if not settings.DATABASES:
  File "/root/askbot-openmooc-venv/lib/python2.7/site-packages/django/utils/functional.py", line 276, in **getattr**
    self._setup()
  File "/root/askbot-openmooc-venv/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/askbot-openmooc-venv/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in **init**
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'askbotopenmooc.settings' (Is it on sys.path?): No module named askbot"

Tnks for any help and advice

regards.
