### ISSUE TITLE
i can continue with installation in item 17

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/askbot-openmooc#5]
Hi, please tell me my error>

su - mooc
cd askbot-devel
source askbot-openmooc-venv/bin/activate
cd askbot-openmooc

(askbot-openmooc-venv)[mooc@felipeurrego askbot-openmooc]$ python manage.py collectstatic
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mooc/askbot-devel/askbot-openmooc-venv/lib/python2.6/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/mooc/askbot-devel/askbot-openmooc-venv/lib/python2.6/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mooc/askbot-devel/askbot-openmooc-venv/lib/python2.6/site-packages/django/core/management/**init**.py", line 252, in fetch_command
    app_name = get_commands()[subcommand]
  File "/home/mooc/askbot-devel/askbot-openmooc-venv/lib/python2.6/site-packages/django/core/management/**init**.py", line 101, in get_commands
    apps = settings.INSTALLED_APPS
  File "/home/mooc/askbot-devel/askbot-openmooc-venv/lib/python2.6/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/home/mooc/askbot-devel/askbot-openmooc-venv/lib/python2.6/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mooc/askbot-devel/askbot-openmooc-venv/lib/python2.6/site-packages/django/conf/__init__.py", line 93, in **init**
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/mooc/askbot-devel/askbot-openmooc-venv/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
    **import**(name)
  File "/home/mooc/askbot-devel/askbot-openmooc/askbotopenmooc/settings.py", line 369, in <module>
    from local_settings import *
  File "/home/mooc/askbot-devel/askbot-openmooc/local_settings.py", line 253, in <module>
    urlpatterns = patterns(
NameError: name 'patterns' is not defined

I have installed django 1.4.1 and everithing

Tnks a lot

**Comment by pitbulk** [comment]
I close this issue since you already got skype support.

**Comment by johnfelipe** [comment]
yes in hangout, tnks all of you
